apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: helloworld-java-spring
      type: image
  tasks:
    - name: build-helloworld-java-spring
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
            # Point to Dockerfile
          value: .
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
           - name: builtImage
             resource: helloworld-java-spring
    - name: deploy-helloworld-java-spring
      taskRef:
        name: deploy-using-kubectl
      resources:
          inputs:
            - name: source
              resource: source-repo
            - name: image
              resource: helloworld-java-spring
              from :
                - build-helloworld-java-spring
      params:
        - name: path
          value: service.yaml

